### ISSUE TITLE
HelpCommand can be more useful if description can be given in configuration

### ISSUE THREAD

**Issue by danaki** [BoShurik/TelegramBotBundle#3]
Like this:

```yml
    app.telegram.command.help:
        class: BoShurik\TelegramBotBundle\Telegram\Command\HelpCommand
        arguments:
            - "@bo_shurik_telegram_bot.command_pool"
            - "Other commands are: /blabla and /bubu"
        tags:
            - { name: bo_shurik_telegram_bot.command }
```

this requires to add one additional parameter to the constructor. Otherwise I'm forced to subclass HelpCommand and override the getDescription() method, while /help is very common command.
