### ISSUE TITLE
Multiple bots feature is broken

### ISSUE THREAD

**Issue by KoNekoD** [BoShurik/TelegramBotBundle#54]
I decided to upgrade from the fork to the updated version but ran into the fact that I can't just assign the bots directive and list my bots, I'm locked out on the old version

**Comment by BoShurik** [comment]
You mean config does not work?
```
boshurik_telegram_bot:
    api:
        default_bot: first
        bots:
            first: "%first_telegram_bot_api_token%"
            second: "%second_telegram_bot_api_token%"
```
